
// User
export const LOGIN = 'LOGIN';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_USER_DATA_FROM_LOCAL_STORAGE = 'GET_USER_DATA_FROM_LOCAL_STORAGE';
export const GET_USER_ACCOUNT_DATA = 'GET_USER_ACCOUNT_DATA';
export const GET_POPULAR_FEED = 'GET_POPULAR_FEED';
export const GET_USERS_SUB_POSTS = 'GET_USER_SUB_POSTS';

// Post
export const SAVE_POST = 'SAVE_POST';
export const UN_SAVE_POST = 'UN_SAVE_POST';
export const SUBMIT_NEW_POST = 'SUBMIT_NEW_POST';
export const UPVOTE_POST = 'UPVOTE_POST';
export const UPVOTE_CURRENT_POST = 'UPVOTE_CURRENT_POST';
export const DOWNVOTE_CURRENT_POST = 'DOWNVOTE_CURRENT_POST';
export const DOWNVOTE_POST = 'DOWNVOTE_POST';
export const LOAD_POST = 'LOAD_POST';
export const LOAD_POST_ERROR = 'LOAD_POST_ERROR';
export const LOAD_POST_COMMENTS = 'LOAD_POST_COMMENTS';
export const LOAD_POST_COMMENTS_ERROR = 'LOAD_POST_COMMENTS_ERROR';

// Comment
export const SAVE_COMMENT = 'SAVE_COMMENT';
export const UN_SAVE_COMMENT = 'UN_SAVE_COMMENT';
export const SUBMIT_NEW_COMMENT = 'SUBMIT_NEW_COMMENT';
export const UPVOTE_COMMENT = 'UPVOTE_COMMENT';
export const DOWNVOTE_COMMENT = 'DOWNVOTE_COMMENT';
export const LOAD_COMMENT_DESCENDANTS = 'LOAD_COMMENT_DESCENDANTS';
export const LOAD_COMMENT_DESCENDANTS_ERROR = 'LOAD_COMMENT_DESCENDANTS_ERROR';
export const LOAD_MORE_COMMENTS = 'LOAD_MORE_COMMENTS';
export const LOAD_MORE_COMMENTS_ERROR = 'LOAD_MORE_COMMENTS_ERROR';

// Sub
export const LOAD_SUB = 'LOAD_SUB';
export const LOAD_SUB_INTO_CURRENT_VIEW = 'LOAD_SUB_INTO_CURRENT_VIEW';
export const LOAD_SUB_ERROR = 'LOAD_SUB_ERROR';
export const LOAD_SUB_POSTS = 'LOAD_SUB_POSTS';
export const LOAD_SUB_POSTS_ERROR = 'LOAD_SUB_POSTS_ERROR';

// Feed
export const GET_LOADED_FEED = 'GET_LOADED_FEED';
export const SWITCH_FEED = 'SWITCH_FEED';
export const LOAD_FEED_INTO_CURRENT_VIEW = 'LOAD_FEED_INTO_CURRENT_VIEW';
